name: Teste backend

defaults:
  run:
    working-directory: "backend/"

on:
  workflow_dispatch:
  push:
    branches:
    - backend
    paths:
    - '.github/workflows/backend-ci.yml'

jobs:
  Teste:
    name: Teste backend
    runs-on: self-hosted

    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install maven
            
    - name: Run tests
      run: mvn clean test

    - name: Build do java
      run: mvn clean package