name: Teste frontend

defaults:
  run:
    working-directory: "frontend/"

on:
  workflow_dispatch:
  push:
    branches:
    - frontend
    paths:
    - '.github/workflows/frontend-ci.yml'

jobs:
  Teste:
    name: Teste frontend
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up nodejs 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'
        
      - name: Getting dependencies
        run: |
          apt-get update && apt-get -y install npm
          npm install -g @angular/cli